### ISSUE TITLE
Having issue with the importer, clouds saved as .ply from cloud compare are not showing in the blender viewport, but are showing within the object listing

### ISSUE THREAD

**Issue by Cambraceres** [TombstoneTumbleweedArt/import-ply-as-verts#12]
I do not know what i am getting wrong here, Ty

**Comment by TombstoneTumbleweedArt** [comment]
I've been away from the computer but I'll investigate. Have you tried the new experimental .PLY in Blender 3.6 yet?

**Comment by Cambraceres** [comment]
I have not, didn't know about it actually but I'll do that this evening and
let you know how it turns out. Thank you

**Comment by Cambraceres** [comment]
These are the files I have tried, all representing a property subject to
topographic survey.

https://drive.google.com/drive/folders/1AKnc-MLtce2be3UoNja3pxW6d_Nl-fMa?usp=sharing

Any help is much appreciated, ty

**Comment by Cambraceres** [comment]
The experimental ply importer in 3.6 also left me with blank space in the
viewport and an object in the outliner, but nothing visible

**Comment by TombstoneTumbleweedArt** [comment]
Thank you for sending files, I see immediately that the issue is with CloudCompare.  In each file, it adds

4   comment Created 2023-06-11T13:26:03
5   obj_info Generated by CloudCompare!

on lines 4 and 5.

Most PLY files contain only one comment line, but most​ importers can handle multiple comments.  It's the obj_info line that is causing Blender's importers to choke.
For an immediate workaround I highly recommend loading your plys into MeshLab (https://www.meshlab.net/) and then just re-export as PLY again.  MeshLab's import/export are the best I know of and exporting from there re-encodes the file to where Blender should be happy.  I've had to use this workflow for years dealing with nonstandard PLYs from Mandelbulb3D and J-Wildfire.  I'll see if I can't get a CloudCompare rule into the import scheme as well.

The new C++ PLY in 3.6 has a couple of bugs yet, but when it works, it is FAST!

________________________________

**Comment by Cambraceres** [comment]
Thank you much Michael I'll let you know any further issue.

**Comment by TombstoneTumbleweedArt** [comment]
Excellent!

~Michael P.
________________________________

**Comment by TombstoneTumbleweedArt** [comment]
Closed issue.

**Comment by TombstoneTumbleweedArt** [comment]
I've been rewriting much of this ahead of the 2.3 release, and your files now import directly from CloudCompare into Blender via Python.
![Cambraceres-GOOD](https://github.com/TombstoneTumbleweedArt/import-ply-as-verts/assets/24717972/54d75075-315d-44c1-b4d8-b17b8dcd24b7)

**Comment by Cambraceres** [comment]
I just saw this. Will test tonight thank you much for the info, but how do
you import something by python? Do you know of any documentation or
tutorials on that?

**Comment by TombstoneTumbleweedArt** [comment]
I was just finishing up the manual on the new version 😀 I can't remember the exact API call but I'll look it up tonight and send it.  Something like bpy.ops.mesh.import_ply.... but don't quote me on that!

~Michael P.
________________________________

**Comment by TombstoneTumbleweedArt** [comment]
Yay, it was easier than I remembered!  Using the current (old) version, the call looks like:

import bpy
Dave = bpy.ops.import_mesh.ply(filepath="F:\\CPP\\A_PLY_As_Verts\\2.ply", use_verts=True)

Where 'Dave' will be the imported object.  On Windows I had to double-backslash the filepath.

This API call will be the same in the 3.0 release so no code-breakers 🙂

And, just for completeness, I forgot I had listed all of this on the Github repo (although it's overly wordy, the above call is all that's needed):
https://github.com/TombstoneTumbleweedArt/import-ply-as-verts/tree/main#python-api
[https://opengraph.githubassets.com/dfcd056b9e885ec3e4791fce5baaf51dd252691af880aa4e4b894dce2c696ad8/TombstoneTumbleweedArt/import-ply-as-verts]<https://github.com/TombstoneTumbleweedArt/import-ply-as-verts/tree/main#python-api>
GitHub - TombstoneTumbleweedArt/import-ply-as-verts: New Blender 3.0* / 3.1 PLY importer v2.0 for point clouds and nonstandard models.<https://github.com/TombstoneTumbleweedArt/import-ply-as-verts/tree/main#python-api>
New Blender 3.0* / 3.1 PLY importer v2.0 for point clouds and nonstandard models. - GitHub - TombstoneTumbleweedArt/import-ply-as-verts: New Blender 3.0* / 3.1 PLY importer v2.0 for point clouds an...
github.com

I've got about two hours left on the docs for 3.0, when it's up to snuff I'll send you the new version a few days ahead of the public release, just because 🙂
________________________________

**Comment by TombstoneTumbleweedArt** [comment]
The manual isn't quite done yet but here's the latest 🙂
Unzip the IPAV-3 file but not the .zip inside, that's the Addon.
________________________________

**Comment by Cambraceres** [comment]
Thank you so much Michael. Your help is much appreciated and your
professional approach is noticed.

**Comment by TombstoneTumbleweedArt** [comment]
You are most welcome! Scenarios like yours are exactly why this project got started, and I'm very happy it helps.

~Michael P.
________________________________

**Comment by Cambraceres** [comment]
Michael, thanks but I see no file or link to a file here

**Comment by TombstoneTumbleweedArt** [comment]
Sorry, I'm not sure where it went.
Here's a Proton Drive link:
https://drive.proton.me/urls/6YTBSE3D0R#e7VLgwf2s6Tz


~Michael P.
________________________________
